postgres:
    container_name: postgres-host
    build: .
    dockerfile: Dockerfile-postgres
    volumes:
        - /data/postgres:/data
    env_file: /etc/acro-api/postgres.env
    restart: always
    log_driver: "fluentd"
redis:
    container_name: redis-host
    image: redis
    volumes:
        - /data/redis:/data
    restart: always
    log_driver: "fluentd"
backend_api:
    build: .
    links:
        - postgres
    env_file: /etc/acro-api/api.env
    restart: always
    domainname: getacro.com
    hostname: api
    log_driver: "fluentd"
