postgres:
    container_name: postgres-host
    build: .
    dockerfile: Dockerfile-postgres
    volumes:
        - /data/postgres:/data
    env_file: /etc/acro-api/postgres.env
    restart: always
backend_api:
    build: .
    links:
        - postgres
    env_file: /etc/acro-api/api.env
    restart: always